FROM node:20-slim

# Install OpenSSL untuk kebutuhan Prisma
RUN apt-get update -y && apt-get install -y openssl && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Perintah yang akan dijalankan ketika container dimulai di mode development
CMD npm install && npx prisma generate && npm run dev
